site_name: Regovar
theme: readthedocs
markdown_extensions:
 - extra
 - nl2br
 - sane_lists
 - abbr
 - attr_list
 - def_list
 - tables 
docs_dir: docs


# TODO: update mkdocs conf when hidden page supported (feature planned for v1.0)
# see : https://github.com/mkdocs/mkdocs/issues/699
pages:
 - 'ACCUEIL': 'index.md'
 - 'INSTALLATION':
    - 'Serveur': 'installation/server.md'
    - 'Client': 'installation/client.md'
    - 'Configuration': 'installation/configuration.md'
 - 'UTILISATEUR': 
    - 'Présentation': 'user/presentation.md'
    - 'Conceptes de base': 'user/concepts.md'
    - 'Analyse - Filtrage': 'user/filtering.md'
    - 'Analyse - Pipeline': 'user/pipeline.md'
    - 'FAQ': 'user/faq.md'
 - 'MAINTENANCE':
    - 'Serveur': 'maintenance/server.md'
    - 'Client': 'maintenance/client.md'
 - 'TUTORIELS':
    - 'Filtrage': 'tutorials/filtering.md'
    - 'Pipeline': 'tutorials/pipeline.md'
    - '&nbsp;&nbsp;- Installation': 'tutorials/pipeline/tuto_001.md'
    - '&nbsp;&nbsp;- Notions de base': 'tutorials/pipeline/tuto_002.md'
    - '&nbsp;&nbsp;- Pipeline Docker': 'tutorials/pipeline/tuto_003.md'
    - '&nbsp;&nbsp;- Ex1: simple': 'tutorials/pipeline/tuto_004.md'
    - 'Autres': 'tutorials/global.md'
 - 'DÉVELOPPEUR':
    - 'Communauté': 'developper/community.md'
    - 'Bonnes pratiques': 'developper/good_practices.md'
    - 'Architecture': 'developper/architecture.md'
    - 'Database': 'developper/database.md'
    - 'Core': 'developper/core.md'
    - 'Modules personalisables': 'developper/modules.md'
    - 'Pirus': 'developper/pirus.md'
    - 'API rest': 'developper/rest.md'
    - 'API cli': 'developper/cli.md'
    - 'Authentification': 'developper/authentication.md'
    - 'Gestion des erreurs': 'developper/errors.md'
    
 
